### ISSUE TITLE
Parameter error: "😱 Could not render this component, see the console."

### ISSUE THREAD

**Issue by TofPlay** [mczachurski/Swiftgger#2]
Hi,
For the api 
```
http://localhost:8080/myapi/?offset=2&limit=10
```
On `Package.swift` I declare:
```swift
 .package(url: "https://github.com/mczachurski/Swiftgger.git", from: "1.2.2")
```
The peace of code for Swiftgger:
```swift
struct MyObject {
    let id: Int
    let name: String
}

var lActions:[APIAction] = []

let lMyApi = APIAction(
    method: .get, route: "/myapi",
    summary: "Some summary",
    description: "some description",
    parameters: [
        APIParameter(name: "offset", parameterLocation: .query,  description: "offset description", required: false),
        APIParameter(name: "limit", parameterLocation: .query, description: "limit description", required: false)
    ],
    responses: [
        APIResponse(code: "200", description: "OK", array: MyObject.self, contentType: "json")
    ],
    authorization: true)

lActions.append(lMyApi)

let lOpenAPI = OpenAPIBuilder(
    title: "MyAPI",
    version: "1.0.0",
    description: "MyAPI description"
    )

lOpenAPI.add(lAPIController)
        .add([
           APIObject(object: MyObject(id: 100, name: "name of the object"))
        ])

```
When I call `http://localhost:8080/swagger.json` Swiftgger generate:
```
{
  "paths": {
    "/myapi": {
      "get": {
        "parameters": [
          {
            "deprecated": false,
            "allowEmptyValue": false,
            "in": "query",
            "name": "offset",
            "description": "offset description",
            "required": false
          },
          {
            "deprecated": false,
            "allowEmptyValue": false,
            "in": "query",
            "name": "limit",
            "description": "limit description",
            "required": false
          }
        ],
        "tags": [
          "MyApi"
        ],
        "deprecated": false,
        "responses": {
          "200": {
            "content": {
              "json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MyObject"
                  }
                }
              }
            },
            "description": "OK"
          }
        },
        "description": "some description",
        "summary": "Some summary"
      }
    }
  },
  "servers": [
    
  ],
  "openapi": "3.0.1",
  "info": {
    "title": "MyAPI",
    "version": "1.0.0",
    "description": "MyAPI description"
  },
  "tags": [
    {
      "name": "MyApi",
      "description": "Test APIs"
    }
  ],
  "components": {
    "schemas": {
      "MyObject": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "name of the object"
          },
          "id": {
            "type": "int",
            "example": "100"
          }
        },
        "required": [
          "id",
          "name"
        ]
      }
    },
    "securitySchemes": {
      
    }
  }
}

```
To run Swagger UI locally I use Docker with this `Dockerfile`:
```
FROM node

RUN npm update npm &&\
    npm install http-server replace

RUN mkdir -p /tmp/swagger
ADD https://github.com/swagger-api/swagger-ui/archive/master.tar.gz /tmp/swagger/swaggerui.tar.gz
RUN tar --strip-components 1 -C /tmp/swagger -xzf /tmp/swagger/swaggerui.tar.gz

RUN mkdir -p /swaggerui/dist/swagger-ui &&\
    mv /tmp/swagger/dist/* /swaggerui/dist/swagger-ui &&\
    rm -rf /tmp/swagger

ENV API_URL http://petstore.swagger.io/v2/swagger.json

RUN echo "'use strict';\
var path = require('path');\
var createServer = require('http-server').createServer;\
var dist = path.join('swaggerui', 'dist');\
var replace = require('replace');\
replace({regex: 'http.*swagger.json', replacement : process.env.API_URL, paths: ['/swaggerui/dist/swagger-ui/index.html'], recursive:false, silent:true,});\
var swaggerUI = createServer({ root: dist, cors: true });\
swaggerUI.listen(8888);" > /swaggerui/index.js

EXPOSE 8888
```
And launch Swagger UI with the command line:
```
docker run --detach --rm --name swaggerui -p 8888:8888 -e "API_URL=http://localhost:8080/swagger.json" swaggerui:latest
```

On the browser I can see this:
![image](https://user-images.githubusercontent.com/1082222/51111191-83625300-17fb-11e9-8e4e-ee03288faac3.png)

And on the console I have this:
![image](https://user-images.githubusercontent.com/1082222/51111569-b3f6bc80-17fc-11e9-9eae-e38495494e7c.png)

The parameters are not defined correctly but I do not see what needs to be done to correct this.

**Comment by eneko** [comment]
I can reproduce this issue at http://editor.swagger.io, by pasting the JSON listed above.

There seem to be two issues:

### 1. Parameters are missing the schema. 
Not sure why this is required, [it might be a bug](https://github.com/swagger-api/swagger-editor/issues/1853), since both the editor and Swagger UI complain about schema missing.

By adding the schema to parameters, we solve this issue:
```yaml
 parameters:
        - deprecated: false
          allowEmptyValue: false
          in: query
          name: offset
          description: offset description
          required: false
          schema:
            type: integer
            format: int64
        - deprecated: false
          allowEmptyValue: false
          in: query
          name: limit
          description: limit description
          required: false
          schema:
            type: integer
            format: int64
```

### 2. Incorrect type specified for integer fields
In the JSON above, `MyObject` has an `id` field of type `int`. The correct type is `integer`, adding format `int64` as follows:

```yaml
MyObject:
      type: object
      properties:
        name:
          type: string
          example: name of the object
        id:
          type: integer
          format: int64
          example: '100'
```
